<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
		<head>
			<title>XML Sitemap Index</title>
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
			<style type="text/css">
				body {
					font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
					color: #333;
					margin: 0;
					padding: 40px 20px;
					background: #fff;
				}
				.container {
					max-width: 1000px;
					margin: 0 auto;
				}
				h1 {
					font-size: 32px;
					font-weight: 700;
					color: #0d122b;
					margin-bottom: 20px;
				}
				p {
					font-size: 14px;
					color: #666;
					line-height: 1.6;
					margin-bottom: 20px;
				}
				p a {
					color: #00bcd4;
					text-decoration: none;
				}
				.info-box {
					background: #f0fbff;
					border-left: 4px solid #00bcd4;
					padding: 15px 20px;
					border-radius: 4px;
					margin-bottom: 30px;
					font-size: 14px;
					color: #0d122b;
				}
				table {
					width: 100%;
					border-collapse: collapse;
					margin-top: 20px;
					box-shadow: 0 4px 15px rgba(0,0,0,0.05);
					border-radius: 8px;
					overflow: hidden;
				}
				th {
					background: #0d122b;
					color: #fff;
					text-align: left;
					padding: 15px 20px;
					font-size: 13px;
					font-weight: 600;
				}
				td {
					padding: 15px 20px;
					border-top: 1px solid #f0f0f0;
					font-size: 14px;
				}
				tr:hover td {
					background: #f9f9f9;
				}
				.sitemap-link {
					color: #00bcd4;
					text-decoration: none;
					display: flex;
					align-items: center;
					gap: 10px;
				}
				.icon {
					display: inline-block;
					width: 18px;
					height: 18px;
					background: #00bcd4;
					border-radius: 3px;
					color: #fff;
					text-align: center;
					font-size: 12px;
					line-height: 18px;
					font-weight: bold;
				}
				footer {
					text-align: center;
					margin-top: 40px;
					font-size: 12px;
					color: #999;
				}
				footer a {
					color: #00bcd4;
					text-decoration: none;
				}
			</style>
		</head>
		<body>
			<div class="container">
				<h1>XML Sitemap Index</h1>
				<p>Generated by Freddway AI, this is an XML Sitemap Index, meant for consumption by search engines.</p>
				<p>You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.</p>
				
				<div class="info-box">
					This XML Sitemap Index file contains <strong><xsl:value-of select="count(//*[local-name()='sitemap'])"/></strong> sitemaps.
				</div>

				<table>
					<thead>
						<tr>
							<th width="70%">Sitemap</th>
							<th width="30%">Last Modified</th>
						</tr>
					</thead>
					<tbody>
						<xsl:for-each select="//*[local-name()='sitemap']">
							<tr>
								<td>
									<a class="sitemap-link">
										<xsl:attribute name="href">
											<xsl:value-of select="*[local-name()='loc']"/>
										</xsl:attribute>
										<span class="icon">S</span>
										<xsl:value-of select="*[local-name()='loc']"/>
									</a>
								</td>
								<td>
									<xsl:value-of select="*[local-name()='lastmod']"/>
								</td>
							</tr>
						</xsl:for-each>
					</tbody>
				</table>

				<footer>
					© 2026 Freddway Coaching & Consulting. All Rights Reserved.
				</footer>
			</div>
		</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
