<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">
    <xsl:output method="html" encoding="UTF-8" indent="yes" />
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>XML Sitemap Index</title>
                <style type="text/css">
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
                        color: #1a1a2e;
                        background: #f8f9fa;
                        margin: 0;
                        padding: 40px 20px;
                    }
                    .container {
                        max-width: 1000px;
                        margin: 0 auto;
                    }
                    h1 {
                        font-size: 32px;
                        font-weight: 700;
                        color: #1a1a2e;
                        margin-bottom: 20px;
                        margin-top: 0;
                    }
                    p {
                        font-size: 14px;
                        color: #666;
                        line-height: 1.6;
                        margin: 0 0 12px 0;
                    }
                    a {
                        color: #1ecbe1;
                        text-decoration: none;
                    }
                    a:hover {
                        text-decoration: underline;
                    }
                    .info-box {
                        background: #fff;
                        border-left: 4px solid #1ecbe1;
                        padding: 24px;
                        margin: 30px 0;
                        border-radius: 4px;
                        font-size: 14px;
                        box-shadow: 0 2px 10px rgba(0,0,0,0.05);
                        color: #1a1a2e;
                    }
                    table {
                        width: 100%;
                        border-collapse: separate;
                        border-spacing: 0;
                        margin-top: 20px;
                        background: #fff;
                        box-shadow: 0 2px 10px rgba(0,0,0,0.05);
                        border-radius: 8px;
                        overflow: hidden;
                    }
                    th {
                        background: linear-gradient(135deg, #1a1a2e 0%, #0f0f1a 100%);
                        color: #fff;
                        padding: 16px 24px;
                        text-align: left;
                        font-size: 14px;
                        font-weight: 600;
                    }
                    td {
                        padding: 16px 24px;
                        border-top: 1px solid #f0f0f0;
                        font-size: 14px;
                        color: #1a1a2e;
                        vertical-align: middle;
                    }
                    tr:hover td {
                        background: #fdfdfd;
                    }
                    .icon {
                        display: inline-flex;
                        align-items: center;
                        justify-content: center;
                        width: 20px;
                        height: 20px;
                        background: #1ecbe1;
                        color: white;
                        border-radius: 3px;
                        margin-right: 12px;
                        font-size: 12px;
                        font-weight: 700;
                        flex-shrink: 0;
                    }
                    .sitemap-link {
                        display: flex;
                        align-items: center;
                    }
                    footer {
                        margin-top: 40px;
                        text-align: center;
                        font-size: 13px;
                        color: #666;
                    }
                    strong {
                        font-weight: 700;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>XML Sitemap Index</h1>
                    <p>Generated by Freddway AI, this is an XML Sitemap Index, meant for consumption by search engines.</p>
                    <p>You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.</p>
                    
                    <div class="info-box">
                        This XML Sitemap Index file contains <strong><xsl:value-of select="count(//*[local-name()='sitemap'])"/></strong> sitemaps.
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th width="75%">Sitemap</th>
                                <th width="25%">Last Modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            <xsl:for-each select="//*[local-name()='sitemap']">
                                <tr>
                                    <td>
                                        <div class="sitemap-link">
                                            <span class="icon">S</span>
                                            <a href="{*[local-name()='loc']}">
                                                <xsl:value-of select="*[local-name()='loc']" />
                                            </a>
                                        </div>
                                    </td>
                                    <td>
                                        <xsl:value-of select="*[local-name()='lastmod']" />
                                    </td>
                                </tr>
                            </xsl:for-each>
                        </tbody>
                    </table>
                    <footer>
                        © 2026 Freddway Coaching &amp; Consulting. All Rights Reserved. | <a href="https://visba.id" target="_blank">Visba</a>
                    </footer>
                </div>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
