<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">
    <xsl:output method="html" encoding="UTF-8" indent="yes" />
    <xsl:template match="/">
        <html>
            <head>
                <title>XML Sitemap Index</title>
                <style type="text/css">
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
                        color: #0d122b;
                        background: #fff;
                        margin: 0;
                        padding: 40px 20px;
                    }
                    .container {
                        max-width: 800px;
                        margin: 0 auto;
                    }
                    h1 {
                        font-size: 32px;
                        margin-bottom: 20px;
                        color: #0d122b;
                    }
                    p {
                        font-size: 14px;
                        color: #666;
                        margin-bottom: 10px;
                    }
                    a {
                        color: #00bcd4;
                        text-decoration: none;
                    }
                    .info-box {
                        background: #f0fbff;
                        border-left: 4px solid #00bcd4;
                        padding: 15px 20px;
                        margin: 20px 0;
                        border-radius: 4px;
                        font-size: 14px;
                    }
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        margin-top: 20px;
                        border: 1px solid #f0f0f0;
                    }
                    th {
                        background: #0d122b;
                        color: #fff;
                        padding: 12px 15px;
                        text-align: left;
                        font-size: 13px;
                    }
                    td {
                        padding: 12px 15px;
                        border-bottom: 1px solid #f0f0f0;
                        font-size: 13px;
                    }
                    tr:hover td {
                        background: #f9f9f9;
                    }
                    .icon {
                        display: inline-block;
                        width: 16px;
                        height: 16px;
                        background: #00bcd4;
                        color: white;
                        text-align: center;
                        line-height: 16px;
                        border-radius: 3px;
                        margin-right: 8px;
                        font-size: 10px;
                    }
                    footer {
                        margin-top: 40px;
                        text-align: center;
                        font-size: 12px;
                        color: #999;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>XML Sitemap Index</h1>
                    <p>Generated by Freddway AI, this is an XML Sitemap Index, meant for consumption by search engines.</p>
                    <p>You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.</p>
                    
                    <div class="info-box">
                        This XML Sitemap Index file contains <strong><xsl:value-of select="count(//*[local-name()='sitemap'])"/></strong> sitemaps.
                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th>Sitemap</th>
                                <th>Last Modified</th>
                            </tr>
                        </thead>
                        <tbody>
                            <xsl:for-each select="//*[local-name()='sitemap']">
                                <tr>
                                    <td>
                                        <a href="{*[local-name()='loc']}">
                                            <span class="icon">S</span>
                                            <xsl:value-of select="*[local-name()='loc']" />
                                        </a>
                                    </td>
                                    <td>
                                        <xsl:value-of select="*[local-name()='lastmod']" />
                                    </td>
                                </tr>
                            </xsl:for-each>
                        </tbody>
                    </table>
                    <footer>
                        © 2026 Freddway Coaching & Consulting. All Rights Reserved.
                    </footer>
                </div>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
